# Site
name: "Pai para sempre"
title: "Pai para sempre"
description: "Ser pai não é uma tarefa fácil, mas vale a pena fazê-lo com todo o seu coração e alma."
logo: 'assets/images/logo_pai_2.png'
favicon: 'assets/images/logo_pai_2.png'
baseurl: "https://paiparasempre.com.br"
google_analytics: 'G-4C84BBGERG'
mailchimp-list:
include: ["_pages"]
permalink: /:title/
disqus: 'pai-para-sempre'
email: contato.paiparasempre@gmail.com
formspree_id: xqkokgjk
recaptcha_key: 6LeR4-AjAAAAAF6WP_74JRCqoN0JK_wpDwjTJ_3S

# Metatags defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      author: "rk"
      image: ""
      categories: ""
      tags: ""
      imageshadow: true
      comments: true

# Authors
authors:
  rk:
    name: Rk
    display_name: Rk
    avatar: 'assets/images/avatar-rk.png'
    email: contato.paiparasempre@gmail.com
    web:
    twitter:
    description: "Autor do Pai para sempre. Ser pai é uma das coisas mais desafiadoras e gratificantes que você fará na vida. É uma jornada cheia de alegria, risos e amor. É uma jornada que o tornará mais forte, mais sábio e mais compassivo."

# Plugins
plugins:
  - jekyll-admin
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
    - year
  layout: archive
  permalinks:
    year: '/ano/:year/'
    category: '/categoria/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true


# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-8011521581149732"
adsense-data-ad-slot-home: "4106562129"
adsense-data-ad-slot: "7280671752"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
