# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

display_url: https://paiparasempre.com.br

media_folder: 'assets/images'

collections:
  - name: 'post'
    label: 'Post'
    folder: '_posts/'
    sort: 'date:asc' # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Comentários", name: "comments", widget: "hidden", default: true}
      - {label: "Título", name: "title", widget: "string", tagname: "h1"}
      - {label: "Data de Publicação", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
      - {label: "Conteúdo", name: "body", widget: "markdown"}
      - {label: "Categorias", name: "categories", widget: "string", required: true, hint: "Separados por espaço"}
      - {label: "Tags", name: "tags", widget: "string", required: false, hint: "Separados por espaço"}
      - {label: "Imagem", name: "image", widget: "string", required: false, hint: "Imagem que ficará no topo do post\nhttps://images.pexels.com/photos/idPhoto/pexels-photo-idPhoto.jpeg"}
      - {label: "Imagem Shadow", name: "imageshadow", widget: "boolean", required: false, default: true}
