---
sitemap: false
---
# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  site_domain: https://paiparasempre.com.br

display_url: https://paiparasempre.com.br
logo_url: https://paiparasempre.com.br/assets/images/logo_pai_3.jpeg

media_folder: 'assets/images'

collections:
  - name: 'post'
    label: 'Post'
    folder: '_posts/'
    sort: 'date:asc' # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Comentários", name: "comments", widget: "hidden", default: true}
      - {label: "Autor", name: "author", widget: "hidden", default: "rk"}
      - {label: "Título", name: "title", widget: "string", tagname: "h1"}
      - {label: "Data de Publicação", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
      - {label: "Conteúdo", name: "body", widget: "markdown"}
      - {label: "Categorias", name: "categories", widget: "list", required: true}
      - {label: "Tags", name: "tags", widget: "string", required: false, hint: "https://images.pexels.com/photos/idPhoto/pexels-photo-idPhoto.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"}
      - {label: "Imagem", name: "image", widget: "image", required: false}
      - {label: "Imagem Shadow", name: "imageshadow", widget: "boolean", required: false, default: true}
  - name: 'produtos'
    label: 'Produtos'
    folder: '_produtos/'
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}'
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Comentários", name: "comments", widget: "hidden", default: false}
      - {label: "Título", name: "title", widget: "string", tagname: "h1"}
      - {label: "Conteúdo", name: "body", widget: "markdown"}
      - {label: "Link", name: "link", widget: "string", tagname: "h1"}
      - {label: "Preço", name: "preco", widget: "string", tagname: "h1"}
      - {label: "Imagem", name: "image", widget: "image", required: false}
      - {label: "Imagem Shadow", name: "imageshadow", widget: "boolean", required: false, default: true}
